http:
  routers:
    traefik:
      rule: "Host(`traefik.dev.astons.me`)"
      service: "api@internal"
      tls:
        domains:
          - main: "dev.astons.me"
            sans:
              - "*.dev.astons.me"
tls:
  certificates:
    - certFile: "/etc/certs/dev.astons.me_cert.pem"
      keyFile: "/etc/certs/dev.astons.me_key.pem"

